### ISSUE TITLE
[hot-reload] error ENC0021: Adding attribute requires restarting the application.

### ISSUE THREAD

**Issue by Mpdreamz** [DamianEdwards/RazorSlices#95]
Hey @DamianEdwards loving RazorSlices,

Trying to enable hot-reload on my project however results in several `ENC0021` errors:

```
/Users/mpdreamz/Projects/docs-builder/.artifacts/obj/Elastic.Documentation.Site/debug/Microsoft.CodeAnalysis.Razor.Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Navigation__TocTree_cshtml.g.cs(4,1): error ENC0021: Adding attribute requires restarting the application.
```

Followed by 

```
error RSG0001: Generated class with name _SecondaryNav already exists. File 'Layout/_SecondaryNav.cshtml' has been ignored.
```

Also being hit by #93 

Reproduce:

* clone: https://github.com/elastic/docs-builder
* `dotnet watch --project src/tooling/docs-builder/ --configuration debug -- serve`

**Comment by DamianEdwards** [comment]
I tried to reproduce this after updating to 0.9.3 but I get an error about invoking `npm`:

```
dotnet watch --project src/tooling/docs-builder/ --configuration debug -- serve
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch ⌚ Building C:\src\GitHub\elastic\docs-builder\src\tooling\docs-builder\docs-builder.csproj ...
dotnet watch 🔨 Build succeeded: C:\src\GitHub\elastic\docs-builder\src\tooling\docs-builder\docs-builder.csproj
info ::e.d.t.f.topwatchFilter:: serve :: Starting...
info ::DocumentationGenerator:: Created documentation set for: docs-builder
info ::DocumentationGenerator:: Source directory: C:\src\GitHub\elastic\docs-builder\docs Exists: True
info ::DocumentationGenerator:: Output directory: C:\src\GitHub\elastic\docs-builder\.artifacts\docs\html Exists: False
info ::Program               :: Find your documentation at http://localhost:3000/
info ::CrossLinkFetcher      :: Getting link index
info ::DocumentationGenerator:: Created documentation set for: docs-builder
info ::DocumentationGenerator:: Source directory: C:\src\GitHub\elastic\docs-builder\docs Exists: True
info ::DocumentationGenerator:: Output directory: C:\src\GitHub\elastic\docs-builder\.artifacts\docs\html Exists: False
info ::DocumentationGenerator:: Resolving tree
info ::DocumentationGenerator:: Resolved tree
info ::e.a.OpenApiGenerator  :: Generating OpenApiDocument Elasticsearch Request & Response Specification
error::m.e.h.i.Host          :: Hosting failed to start
info ::e.d.t.f.topwatchFilter:: serve :: Finished in '00:00:01.7770734'
error::Program               :: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'npm' with working directory 'C:\src\GitHub\elastic\docs-builder\src\Elastic.Documentation.Site'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Documentation.Builder.Http.ParcelWatchService.StartAsync(CancellationToken cancellationToken) in C:\src\GitHub\elastic\docs-builder\src\tooling\docs-builder\Http\ParcelWatchService.cs:line 17
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Documentation.Builder.Http.DocumentationWebHost.RunAsync(CancellationToken ctx) in C:\src\GitHub\elastic\docs-builder\src\tooling\docs-builder\Http\DocumentationWebHost.cs:line 85
   at Documentation.Builder.Cli.Commands.Serve(String path, Int32 port, CancellationToken ctx) in C:\src\GitHub\elastic\docs-builder\src\tooling\docs-builder\Cli\Commands.cs:line 44
   at ConsoleAppFramework.ConsoleApp.ConsoleAppBuilder.RunCommand0Async(String[] args, Int32 commandDepth, Int32 escapeIndex, ConsoleAppContext context, CancellationToken cancellationToken) in C:\src\GitHub\elastic\docs-builder\.artifacts\obj\docs-builder\debug\ConsoleAppFramework\ConsoleAppFramework.ConsoleAppGenerator\ConsoleApp.Builder.g.cs:line 145
   at Documentation.Builder.Cli.CheckForUpdatesFilter.InvokeAsync(ConsoleAppContext context, CancellationToken ctx) in C:\src\GitHub\elastic\docs-builder\src\tooling\docs-builder\Cli\CheckForUpdatesFilter.cs:line 18
   at Elastic.Documentation.Tooling.Filters.CatchExceptionFilter.InvokeAsync(ConsoleAppContext context, CancellationToken cancellationToken) in C:\src\GitHub\elastic\docs-builder\src\tooling\Elastic.Documentation.Tooling\Filters\CatchExceptionFilter.cs:line 17
   at Elastic.Documentation.Tooling.Filters.StopwatchFilter.InvokeAsync(ConsoleAppContext context, CancellationToken cancellationToken) in C:\src\GitHub\elastic\docs-builder\src\tooling\Elastic.Documentation.Tooling\Filters\StopwatchFilter.cs:line 22
   at ConsoleAppFramework.ConsoleApp.RunWithFilterAsync(String commandName, String[] args, Int32 commandDepth, Int32 escapeIndex, ConsoleAppFilter invoker) in C:\src\GitHub\elastic\docs-builder\.artifacts\obj\docs-builder\debug\ConsoleAppFramework\ConsoleAppFramework.ConsoleAppGenerator\ConsoleApp.g.cs:line 348
dotnet watch ❌ [docs-builder (net9.0)] Exited with error code 1
dotnet watch ⏳ Waiting for a file to change before restarting ...
```

Can you try seeing if the issue still reproduces for you? Also, which .NET SDK version are you using? I tried it with 9.0.302

**Comment by DamianEdwards** [comment]
I just pushed a fix for #93. Could you try this again please using version `0.9.4` and see if it still reproduces for you?

**Comment by Mpdreamz** [comment]
Can confirm everything works beautifully when providing:

>  <MinVerSkip Condition="'$(Configuration)' == 'Debug'">true</MinVerSkip>

Thanks @DamianEdwards this further boost our enjoyment of RazorSlices 😸 !

**Comment by Mpdreamz** [comment]
Yep!
